"""Add events and event_reminders tables

Revision ID: 8d24cdcc873d
Revises: 7e28c66b7bc8
Create Date: 2025-08-10 04:49:58.938250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d24cdcc873d'
down_revision = '7e28c66b7bc8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###